compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

packageExtensions:
  '@prisma/client@*':
    dependencies:
      '.prisma/client': '*'
  'prisma@*':
    dependencies:
      '.prisma/client': '*'
