nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    AUTH_ENABLED: false
    SERVICE_TEAM: wa
    SERVICE_NAME: wa-reporting-frontend
    SERVICE_ENVIRONMENT: aat
